### ISSUE TITLE
Questions about challenge configuration in Test-Dev phase

### ISSUE THREAD

**Issue by SgtVincent** [allenai/robothor-challenge#11]
Hi! In the released code, Controller parameters are specified in the file `./robothor-challenge/dataset/challenge_config.yaml`, including 
```
initialize:
    rotateStepDegrees: 30
    visibilityDistance: 1.0
    gridSize: 0.25
    ...
```
Now I can train/test the model under this set of parameters or customize it. e.g. 
```
initialize:
    rotateStepDegrees: 45
    visibilityDistance: 2.0
    gridSize: 0.3
    ...
```
  Yet I wonder what scope of code should we submit to the eval AI once provided. Could I customize this configuration file in the Test-Dev phase? Or these parameters are simply fixed for this challenge and we only submit a model which outputs choice of actions to the eval AI system? 

Your answer really matters for my following plan. Thanks for your help!
